---
name: Update
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: 11 7 * * *

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: pdm-project/setup-pdm@main
        name: Setup Python and PDM
        with:
          python-version: 3.9
      - name: Update requirements
        run: make update
      - name: Install the program
        run: make install
      - name: Run tests
        run: make all
      - name: Commit files
        run: |
          rm -r .git/hooks
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt docs/requirements.txt requirements-dev.txt
          git diff-index --quiet HEAD \
            || git commit -m "chore: update dependency requirements"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
